import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto">
          <div className="header bg-black p-4 flex justify-between items-center w-full">
            <div className="logo">
              <Image
                src="/logo.png"
                alt="Next.js logo"
                width={180}
                height={20}
                priority
              />
            </div>
            <div className="menu">
              <button className="btn border px-8 py-2 rounded-full cursor-pointer">Let's Talk</button>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
